### PR TITLE
extract methods

### PR DESCRIPTION
**Pull request by ceduliocezar**
Improve code readability and reusability

### CODE REVIEW

**Comment by alorma** [comment]
Hi @ceduliocezar can you please rebase your branch from my master? I've fixed travis build.

Also, if you want, add yourself to the Contributors, at the end of readme

**Comment by alorma** [comment]
Thanks @ceduliocezar

**Comment by ceduliocezar** [comment]
My pleasure.

I forgot to add myself as contributor, I will do it later =)

**Comment by alorma** [comment]
If you are going to add the library to any app, and want to be listed, open an issue and i will add into readme

**Pull request merged**
